Referenced by issue #128912, module 'bpy_extras' has no attribute 'image_utils'
