Referenced by issue #112851, bpy.ops undo argument doesn't work if the main operator has UNDO in bl_options
