Referenced by issue #85648, macOS: addons fail to import due to Python 3.9 libraries linking against libz.dylib
