Referenced by issue #62736, Inconsistent behavior of bpy.utils.user_resource( ) function
