Referenced by issue #61593, pyrna_enum_to_py complains when iterate area.regions
