Referenced by commit 6e2da0883f6, Fix T61309: mesh_utils.triangle_random_points fails with a TypeError
