Referenced by issue #122305, Segmentation fault while generating Python API documents
