Referenced by issue #44137, bpy.path.is_subdir
