Referenced by issue #106740, Sequencer, Python bug in scene.sequence_editor.sequences.new_image()
