Referenced by issue #87944, Python API Function `bpy.data.meshes.mesh_from_object()` No Longer Works
